version: "3"
services:
  rmq-mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rmq-mqtt
    hostname: rmq-mqtt
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "1883:1883"
      - "15672:15672"
